// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE2Mq55mB22exvwJMJaowctoDLVe0o8os',
    appId: '1:283446175761:web:a4c275a6a21d39b54469b0',
    messagingSenderId: '283446175761',
    projectId: 'todolistapp-c76b2',
    authDomain: 'todolistapp-c76b2.firebaseapp.com',
    storageBucket: 'todolistapp-c76b2.appspot.com',
    measurementId: 'G-1CSZ909E26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPamC9FhuT0oVvJjQXf0O5peNCtsxsKHQ',
    appId: '1:283446175761:android:3acb5bb8d3a8714c4469b0',
    messagingSenderId: '283446175761',
    projectId: 'todolistapp-c76b2',
    storageBucket: 'todolistapp-c76b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU1kO9wu3xq3kXWci0vrqVb6JfOh0xn2s',
    appId: '1:283446175761:ios:06f0bb576fa2e86a4469b0',
    messagingSenderId: '283446175761',
    projectId: 'todolistapp-c76b2',
    storageBucket: 'todolistapp-c76b2.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU1kO9wu3xq3kXWci0vrqVb6JfOh0xn2s',
    appId: '1:283446175761:ios:06f0bb576fa2e86a4469b0',
    messagingSenderId: '283446175761',
    projectId: 'todolistapp-c76b2',
    storageBucket: 'todolistapp-c76b2.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE2Mq55mB22exvwJMJaowctoDLVe0o8os',
    appId: '1:283446175761:web:2abc307abe26b6f94469b0',
    messagingSenderId: '283446175761',
    projectId: 'todolistapp-c76b2',
    authDomain: 'todolistapp-c76b2.firebaseapp.com',
    storageBucket: 'todolistapp-c76b2.appspot.com',
    measurementId: 'G-WC1Q4762YY',
  );
}
